plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# IMPORTANT: before pushing live, uncomment eddymikes.me baserul and comment out blank baseurl

baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "https://eddymikes.me" # the subpath of your site, e.g. /blog
url: "https://emikes919.github.io" # the base hostname & protocol of your site, e.g. http://example.com